### ISSUE TITLE
Linter currently doesn't work in Firefox

### ISSUE THREAD

**Issue by kulla** [vroland/mwlint#15]
I get the following error:

    Cross-Origin Request Blocked: The Same Origin Policy disallows
    reading the remote resource at https://tools.wmflabs.org/mwlint/examples/.
    (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by kulla** [comment]
Error in chromium:

    https://tools.wmflabs.org/mwlint/examples/: No 'Access-Control-Allow-Origin' header is
    present on  the requested resource. Origin 'https://de.wikibooks.org' is therefore not
    allowed access. The response had HTTP status code 404.

and

    Failed to load resource https://tools.wmflabs.org/mwlint/examples/: the server
    responded with a status of 404 ()

**Comment by vroland** [comment]
The service was not running. Could be tool server maintainance.
