### ISSUE TITLE
Two editor views currently in Firefox

### ISSUE THREAD

**Issue by kulla** [vroland/mwlint#16]
Screenshot:

![screenshot from 2018-06-17 11-31-05](https://user-images.githubusercontent.com/1327215/41506647-24b06d94-7222-11e8-8b55-bce4dd26ff94.png)

**Comment by vroland** [comment]
This happens when you turn on syntax highlighting (pen icon). We should try to detect that in the setup script...

**Comment by vroland** [comment]
currently mitigatined by removing syntax highlighting from the toolbar.
