### ISSUE TITLE
Proof steps should not be nested

### ISSUE THREAD

**Issue by vroland** [vroland/mwlint#40]
See proof in https://de.wikibooks.org/wiki/Mathe_f%C3%BCr_Nicht-Freaks:_Supremum_und_Infimum_bestimmen_und_beweisen#Anker:Menge_von_Folgengliedern

@kulla Suggest to use list instead or are nested proof steps actually allowed?

**Comment by vroland** [comment]
How would a proof step list template solve nesting?

**Comment by kulla** [comment]
It could be included. However, I think nested proof steps are the better solution since sometimes one needs additional text after and before proof steps...

**Comment by vroland** [comment]
All right, nested proof steps will be allowed then.
